# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "ehci_pci" "ahci" "nvme" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" "amdgpu" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2582c079-625f-45d0-a7d5-fd5fb46e80f5";
      fsType = "btrfs";
      options = [ "subvol=@/root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/2582c079-625f-45d0-a7d5-fd5fb46e80f5";
      fsType = "btrfs";
      options = [ "subvol=@/home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/2582c079-625f-45d0-a7d5-fd5fb46e80f5";
      fsType = "btrfs";
      options = [ "subvol=@/nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BD8E-41D6";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.ens33.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
